### ISSUE TITLE
Add to jamjs.org package repository.

### ISSUE THREAD

**Issue by jgornick** [asciidisco/Backbone.Marionette.Handlebars#1]
I've already added backbone.marionette to jamjs package repository @ http://jamjs.org/packages/#/details/Backbone.Marionette.

I also have a PR waiting in backbone.marionette to officially add jamjs configuration to package.json @ https://github.com/derickbailey/backbone.marionette/pull/217

**Comment by asciidisco** [comment]
Hey,
sorry for replying so late.
I was on a longer vacation.

Bower & Jam support will be added asap.

**Comment by jgornick** [comment]
Awesome! Thanks!

**Comment by asciidisco** [comment]
I´ve published the lib to the jam repo & added a component.json for bower.
So, if you´re using volo, jam or bower (yeoman), you should be save.
