### ISSUE TITLE
Bower, requirejs and backbone.marionette.handlebars

### ISSUE THREAD

**Issue by apierr** [asciidisco/Backbone.Marionette.Handlebars#3]
I am using `Bower` to install `backbone.marionette.handlebars`.  
When I try to use it by means of `requirejs` I get the following error:

```
 http://localhost/src/js/backbone.marionette.js 404 (Not Found)
```

If I try to use just marionette it works!

Here is the code about `require.conf` (1)

For the full code you can visit 
https://github.com/antonioJs/CoCoTask/pull/1/files

---

(1)

``` javascript
require.config({
    paths: {
        marionette: vendorDir + 'backbone.marionette/lib/amd/backbone.marionette.min',
        marionetteHandlebars: vendorDir + 'Backbone.Marionette.Handlebars/backbone.marionette.handlebars.min'
    },
    shim: {
        marionetteHandlebars: {
            deps: ['marionette']
        }
    }
});
```

**Comment by stephanebachelier** [comment]
Your config is not correct.

I've not tested but reading the wiki : 
- marionette should be exported as 'backbone.marionette' 
- marionetteHandlebars should be exported as 'backbone.marionette.handlebars'.

So I would write something like: 

```
require.config({
    paths: {
        marionette: vendorDir + 'backbone.marionette/lib/amd/backbone.marionette.min',
        marionetteHandlebars: vendorDir + 'Backbone.Marionette.Handlebars/backbone.marionette.handlebars.min'
    },
    shim: {
        marionette: {
            exports: 'backbone.marionette'
        },
        marionetteHandlebars: {
            deps: ['marionette'],
            exports: 'backbone.marionette'
        }
    }
});
```

**Comment by apierr** [comment]
thanks @stephanebachelier your solutions fix the issue.
