### ISSUE TITLE
Marionette.View.templateHelpers are missing the context

### ISSUE THREAD

**Issue by bernharduw** [asciidisco/Backbone.Marionette.Handlebars#6]
When using the templateHelpers hash, helpers are called, but this is not set to the serialized Data as stated in the [Marionette docs](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.view.md#accessing-data-within-the-helpers).

Example:

``` javascript
var view = Backbone.Marionette.ItemView.extend({
            template: template,
            templateHelpers: {
                slug: function() {
                    return this.id;
                }
            },
            tagName: 'li'
        });
```

**Comment by asciidisco** [comment]
Hi @bernharduw,
sorry to not have reacted to this issue in time.
I considered this Plugin obsolete since some time ago.
Closing this.
