### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by jarrodpayne** [asciidisco/Backbone.Marionette.Handlebars#7]
I see that you mentioned this project could be obsolete now. Any suggestions? I'm having one heck of a time trying to get Handlebars, RequireJS, and Marionette all working in sync

**Comment by asciidisco** [comment]
I personally believe that it is obsolete, because to get the templates in your view, they just need to be a function:

```
define(['hbs!myTemplate'], function (template) {
  var MyView = Backbone.Marionette.ItemView.extend({
    template: template,
    model: new Backbone.Model({name: "Steve"})
  });
});
```

That should do the trick.

**Comment by jarrodpayne** [comment]
Ah gotcha. I agree. I was able to get Handlebars working exactly like you say here using the [hbs plugin](https://github.com/SlexAxton/require-handlebars-plugin) your referring to with `hbs!`. For a while, I was trying to get these two working in tandem. Thanks!
