### ISSUE TITLE
how to register a helper

### ISSUE THREAD

**Issue by chilijung** [asciidisco/Backbone.Marionette.Handlebars#8]
Hi, I'm using this plugin and I'm wondering how could I register a handlebar helper?

**Comment by asciidisco** [comment]
Hi @chilijung,

I highly recommend not to use this plugin anymore (will add a Warning/Notice to the README),
please check this http://stackoverflow.com/questions/19863285/using-precompiled-handlebars-templates-with-marionette# thread & my note in this issue: https://github.com/asciidisco/Backbone.Marionette.Handlebars/issues/7; it should be obvious how to register helpers following the alternate way of using Handlebars with Marionette.
